# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'tp-docker'
        repository: 'tpeterson66/django-todo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      inputs:
        containerRegistry: 'tp-docker'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'tp-docker'
        repository: 'tpeterson66/django-todo'
        command: 'push'