# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Docker Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'tp-docker'
        repository: 'tpeterson66/django-todo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'tp-docker'
        command: 'login'
    - task: Docker@2
      displayName: Docker Push Build ID
      inputs:
        containerRegistry: 'tp-docker'
        repository: 'tpeterson66/django-todo'
        command: 'push'
    - task: Docker@2
      displayName: Docker Push Latest
      inputs:
        containerRegistry: 'tp-docker'
        repository: 'tpeterson66/django-todo'
        command: 'push'
        tags: 'latest'
# - stage: Push
#   displayName: Push image to Docker Hub
#   jobs:  
#   - job: Push
#     displayName: Docker Push to Docker Hub
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps: