version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    networks:
        - backend
    environment:
      - POSTGRES_NAME=TodoDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="thisSuperSECUREPassword2020!"
      - POSTGRES_HOST="10.132.0.2"
      - POSTGRES_PORT=5432

  app:
    image: tpeterson66/django:latest
    container_name: django-todo
    restart: always
    networks:
        - backend
    ports: 
        - 8000:8000
    volumes:
        - ./db-data:var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: "thisSuperSECUREPassword2020!"
        POSTGRES_HOST: db

networks:
    backend: